language: ruby
bundler_args: --without development
script: "bundle exec rake test"
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.0
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0" STRICT_VARIABLES=yes
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0" STRICT_VARIABLES=yes
notifications:
  email: false

before_install:
  - gem update --system 2.1.11
  - gem --version
